name: Trigger PR in dhis2-core with contracts from PR in dhis2-api-contracts

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trigger-pr-with-contracts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dhis2-api-contracts PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: temp-api-contracts

      - name: Checkout dhis2-core to workspace root
        uses: actions/checkout@v4
        with:
          repository: dhis2/dhis2-core
          token: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}
          path: .  # Checkout to root instead of subdirectory

      - name: Copy contracts
        run: |
          # Copy contracts from temp directory to current location
          cp -r temp-api-contracts/contracts/ dhis-2/dhis-test-web-api/src/test/resources/
          rm -rf temp-api-contracts

      - name: Create branch and commit with signed commit
        uses: flex-development/gh-commit@1.0.0
        with:
          branch: "sync-from-api-contracts-pr-${{ github.event.number }}"
          create: true
          message: "Sync from api-contracts PR ${{ github.event.pull_request.html_url }}"
          token: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Sync contracts from api-contracts PR #${{ github.event.number }}" \
            --body "Auto-generated from api-contracts PR: ${{ github.event.pull_request.html_url }}
          
          ## Original PR Details
          - **Title:** ${{ github.event.pull_request.title }}
          - **Author:** @${{ github.event.pull_request.user.login }}
          - **Branch:** \`${{ github.head_ref }}\`" \
            --head "sync-from-api-contracts-pr-${{ github.event.number }}" \
            --base master